---
title: "Text genegator with Keras and R"
output: html_notebook
---

Load packages:

```{r, message=FALSE}
library(keras)
library(readr)
library(stringr)
library(purrr)
library(tokenizers)
source('utils.R')
maxlen <- 40
```

Read the dataset:

```{r}
path <- get_file(
  'nietzsche.txt', 
  origin='https://s3.amazonaws.com/text-datasets/nietzsche.txt'
)
text <- read_lines(path)
head(text, 20)
```

Tokenize text:

```{r}
text <- text %>%
  str_to_lower() %>%
  str_c(collapse = "\n") %>%
  tokenize_characters(strip_non_alphanum = FALSE, simplify = TRUE)
head(text, 100)
```

Chceck unique characters in text:

```{r}
chars <- text %>% unique()
chars
```

Create predictors (sequences) and predicted values (next letter after the sequence):

```{r}
data <- create_sequences(maxlen, text)
x <- data[[1]]
y <- data[[2]]
```

Build the model:

```{r}
model <- keras_model_sequential()
model %>%
  layer_lstm(128, input_shape = c(maxlen, length(chars))) %>%
  layer_dense(length(chars)) %>%
  layer_activation("softmax")

model %>% compile(
  loss = "categorical_crossentropy", 
  optimizer = optimizer_adamax(lr = 0.01)
)

model %>% fit(x, y,
  batch_size = 128,
  epochs = 5,
  callbacks = callback_tensorboard("logs/text")
)
```

Predict on a new sentence:

```{r}
sentence <- "speak seriously, there are good grounds "
predict_text(sentence, 50, model)
```

